"""Durable OHLCV collection progression — one "a run started" counter per source.

WHY THIS TABLE EXISTS
---------------------
A3c's symbol rotation used to derive its phase from an absolute cadence bucket.
Three reviews showed that family cannot carry a fairness proof: the offsets a
`bucket % N` scheme can ever produce collapse to the coset generated by
gcd(execution_stride, N) — measured at N=56 with an every-fourth-cadence pattern,
42 of 56 symbols were never reached. Projecting through a prime moved the hole to
one stride instead of many, and moving the prime only moved it again (identical
failure measured at 251, 257, 509, 65537).

The problem is that WALL-CLOCK TIME is chosen by the environment, and production
enforces nothing about it: there is no persistent APScheduler jobstore, no
minimum-uptime invariant, no recovery guarantee. So the collector stops asking the
clock and counts its OWN executions instead. `run_seq % N` then visits every start
position within N executed runs under ANY execution pattern.

WHAT THE VALUE MEANS
--------------------
Exactly: "a collection run for this source has STARTED." It is deliberately not a
claim that the run succeeded, completed, attempted every symbol or timeframe,
persisted a bar, advanced coverage, or advanced a watermark. A run that increments
this and dies one millisecond later has still consumed a sequence value — that is
the point, and it is what prevents a crash-looping run from replaying the same
prefix of the universe forever.

NOT A COVERAGE CURSOR. It says nothing about which bars exist or how far back
history reaches; A4 still owns historical completeness and gap repair.

THE create_all TRAP — WHY EVERY CONSTRAINT IS DECLARED HERE
-----------------------------------------------------------
`scripts/migrate.py` runs `Base.metadata.create_all` BEFORE applying pending .sql
files, so on a fresh database THIS MODEL creates the table and the migration's
`CREATE TABLE IF NOT EXISTS` is a silent no-op. Any constraint declared only in
SQL would therefore never reach such a database while the ledger still recorded
the migration as applied. Both declarations are asserted to agree in
tests/test_ohlcv_progression.py.
"""

from __future__ import annotations

from sqlalchemy import BigInteger, CheckConstraint, Column, DateTime, String, text

from app.database import Base


class OhlcvCollectionProgress(Base):
    """One row per source. Small on purpose: three columns, one of them advisory."""

    __tablename__ = "ohlcv_collection_progress"

    # Logical key — the same `source` the watermark read and the row write use, so
    # a second venue can never advance binance's fairness sequence.
    source = Column(String, primary_key=True, nullable=False)

    # The progression. Monotonic; advanced by exactly one per executed run.
    run_seq = Column(BigInteger, nullable=False, server_default=text("0"))

    # Advisory ONLY — never read by a correctness path. A shadow job's staleness is
    # deliberately excluded from the global /health `degraded` aggregate, so without
    # this an operator cannot tell an advancing cursor from one stuck for a week.
    updated_at = Column(DateTime(timezone=True), nullable=False,
                        server_default=text("now()"))

    __table_args__ = (
        CheckConstraint("run_seq >= 0", name="ck_ohlcv_collection_progress_seq"),
        CheckConstraint("length(btrim(source)) > 0",
                        name="ck_ohlcv_collection_progress_source"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (f"<OhlcvCollectionProgress source={self.source!r} "
                f"run_seq={self.run_seq}>")
