"""CP-OHLCV-A3c — SYMBOL fairness from a DURABLE EXECUTED-RUN SEQUENCE.

WHAT THIS FILE USED TO TEST, AND WHY IT NO LONGER DOES
------------------------------------------------------
It used to pin a prime projection, `offset = (bucket % 251) % count`, introduced
because `bucket % count` collapsed to the coset generated by gcd(stride, count) —
at count = 56 with an every-fourth-cadence execution pattern, 42 of 56 symbols
were measured as never reached. The prime removed that hole but left one at
stride 251, and an architecture review then proved the whole family unfixable:
moving the prime only moves the hole (measured identical at 251, 257, 509,
65537), because the ENVIRONMENT chooses which cadence buckets are ever executed
and production enforces nothing about that choice.

So the clock is gone. `rotation_offset(count, run_seq)` counts the collector's own
executions. The bound below therefore holds for EVERY wall-clock execution
pattern, including ones that defeat any absolute-time finite-modulus design —
`test_an_adversarial_schedule_that_defeats_any_time_modulus` is exactly that case.

THE BOUND: every symbol is FIRST at least once within `count` EXECUTED runs.
This is ATTEMPT fairness — not completion, not persistence.
"""

from __future__ import annotations

import pytest

from app.services import ohlcv_collector_job as J
from app.services.ohlcv_collector_job import UNIVERSE_CAP, rotation_offset

SIZES = [1, 2, 3, 4, 8, 12, 16, 20, 24, 55, 56, 57, 58, 59, 60, 61, 63, 64,
         127, 128, 249, 250]


def offsets_over(count, runs, start=0):
    """Offsets seen over `runs` EXECUTED runs, whatever the wall clock did."""
    return [rotation_offset(count, start + i) for i in range(runs)]


# ══ THE BOUND ══════════════════════════════════════════════════════════════
@pytest.mark.parametrize("count", SIZES)
def test_every_start_position_occurs_within_count_executed_runs(count):
    assert set(offsets_over(count, count)) == set(range(count))


@pytest.mark.parametrize("count", SIZES)
@pytest.mark.parametrize("start", [0, 1, 7, 250, 251, 999, 10 ** 9])
def test_the_bound_holds_from_any_starting_sequence(count, start):
    """Restart, redeploy and rollback all resume from wherever the DURABLE value
    got to; none of them re-phases anything."""
    assert set(offsets_over(count, count, start=start)) == set(range(count))


@pytest.mark.parametrize("count", [4, 56, 57, 60, 127, 250])
def test_the_worst_gap_between_two_reaches_is_exactly_count(count):
    last, worst = {}, 0
    for i in range(count * 4):
        off = rotation_offset(count, i)
        if off in last:
            worst = max(worst, i - last[off])
        last[off] = i
    assert worst == count


# ══ THE CASES THAT KILLED EVERY TIME-DERIVED DESIGN ════════════════════════
@pytest.mark.parametrize("count", [56, 60, 64, 128, 248])
@pytest.mark.parametrize("gap", [1, 2, 3, 4, 5, 7, 8, 16, 251, 502, 100000])
def test_arbitrary_execution_gaps_change_nothing(count, gap):
    """`gap` is how many CADENCE BUCKETS were skipped between executions. Under
    every previous design this chose the phase; here it cannot, because a bucket
    that is never executed never advances the sequence."""
    assert set(offsets_over(count, count)) == set(range(count))


def test_an_adversarial_schedule_that_defeats_any_time_modulus():
    """The decisive case.

    An adversary picks executed wall-clock buckets all congruent mod M. Against
    `f(bucket)` for ANY finite modulus M this freezes the offset; against a
    counter it is not even an input. Both halves are asserted, so the test proves
    the difference rather than asserting the happy path alone.
    """
    count, M = 57, 251
    adversarial_buckets = [1000 + j * M for j in range(4 * count)]

    time_derived = {(b % M) % count for b in adversarial_buckets}
    assert len(time_derived) == 1, "the adversarial sequence must lock a time modulus"

    counter_derived = {rotation_offset(count, i) for i in range(len(adversarial_buckets))}
    assert counter_derived == set(range(count)), \
        "the durable counter must be immune to the same sequence"


def test_restart_between_every_single_run_changes_nothing():
    """A restart loses process state; the sequence lives in the database."""
    import importlib
    count, seen = 57, set()
    for i in range(count):
        importlib.reload(J)          # brand-new module state every run
        seen.add(J.rotation_offset(count, i))
    assert seen == set(range(count))


def test_the_offset_is_a_pure_function_of_sequence_and_count():
    for _ in range(5):
        assert rotation_offset(57, 12345) == rotation_offset(57, 12345)


# ══ NO CLOCK MAY RE-ENTER ══════════════════════════════════════════════════
def test_no_wall_clock_reaches_the_offset():
    """A static guard, because this is the exact regression that cost four CPs."""
    import ast
    import inspect
    tree = ast.parse(inspect.getsource(rotation_offset).lstrip())
    names = {getattr(n, "id", None) for n in ast.walk(tree)}
    names |= {getattr(n, "attr", None) for n in ast.walk(tree)}
    for forbidden in ("now", "datetime", "utcnow", "time", "timestamp",
                      "cadence_seconds", "monotonic"):
        assert forbidden not in names, f"{forbidden} is back in the offset"


def test_the_signature_takes_a_sequence_not_a_moment():
    import inspect
    params = list(inspect.signature(rotation_offset).parameters)
    assert params == ["count", "run_seq"]


def test_the_dead_prime_constant_is_gone():
    """Leaving it would invite a future caller to reintroduce the old family."""
    assert not hasattr(J, "SYMBOL_ROTATION_PERIOD")


# ══ DEGENERATE INPUT ═══════════════════════════════════════════════════════
def test_degenerate_inputs():
    assert rotation_offset(0, 5) == 0
    assert rotation_offset(1, 999) == 0
    assert rotation_offset(-3, 5) == 0
    with pytest.raises(ValueError, match="run_seq"):
        rotation_offset(10, -1)


def test_offsets_stay_in_range_across_the_whole_allowed_universe():
    for count in (1, 2, UNIVERSE_CAP - 1, UNIVERSE_CAP):
        for seq in (0, 1, count - 1, count, 10 ** 12):
            assert 0 <= rotation_offset(count, seq) < count


# ══ UNIVERSE CHURN ═════════════════════════════════════════════════════════
@pytest.mark.parametrize("a,b", [(55, 56), (56, 57), (57, 56), (57, 58), (58, 59),
                                 (59, 60), (60, 61), (63, 64), (64, 63),
                                 (249, 250), (250, 249)])
def test_stable_symbols_regain_the_bound_after_churn_settles(a, b):
    """During churn the universe itself is changing, so no bound is claimed. Once
    it stabilises the bound is simply the new count."""
    core = min(a, b)
    seq = 0
    for _ in range(300):                       # churn
        seq += 1
    seen = set()
    for _ in range(core):                      # stabilised
        seen.add(rotation_offset(core, seq) % core)
        seq += 1
    assert seen == set(range(core))
