"""CP-OHLCV-A3c REPAIR v4 — SYMBOL fairness under execution strides.

THE BLOCKER THIS FILE EXISTS FOR
--------------------------------
`rotation_offset` was `bucket % count`. That is fair only when executed cadence
buckets advance ONE AT A TIME. If the job executes on a fixed STRIDE s, the
offsets it can ever produce collapse to the coset generated by gcd(s, count).
Measured on the previous commit, with no failures at all:

    count = 56, stride = 2  ->  28 of 56 symbols never reached
    count = 56, stride = 4  ->  14 of 56 symbols never reached, forever
    count = 60, stride = 4  ->  15 of 60 symbols never reached, forever

The universe size is not ours to choose — it is however many active crypto
assets exist — so "production happens to be 57, which is coprime with 4" is not
a correctness argument. It is luck, and the review that found this said so.

THE REPAIR: project the bucket through a PRIME strictly larger than
UNIVERSE_CAP before reducing modulo the universe size.

    offset = (bucket % SYMBOL_ROTATION_PERIOD) % count        # 251, prime

PROOF. Let the executed buckets be b_j = b0 + j*s.
  * 251 is prime, so gcd(s, 251) = 1 for every stride s it does not divide.
    Then j -> b_j mod 251 is a bijection of Z_251: over any 251 consecutive
    EXECUTED runs it takes every value in 0..250.
  * count <= UNIVERSE_CAP = 250 < 251, so reducing those 251 values modulo
    `count` is ONTO 0..count-1.
Composing, every offset — including the one that puts any given symbol FIRST —
occurs at least once per 251 executed runs, for EVERY universe size, EVERY
number of symbols reached per run, and EVERY stride except a multiple of 251.
That excluded case is asserted below rather than left implicit.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timedelta, timezone

import numpy as np
import pandas as pd
import pytest

from app.services import ohlcv_collector_job as J
from app.services.ohlcv_collector_job import (STORAGE_TIMEFRAMES,
                                              SYMBOL_ROTATION_PERIOD,
                                              UNIVERSE_CAP, CollectionResult,
                                              rotation_offset)

UTC = timezone.utc
T0 = datetime(2026, 8, 1, tzinfo=UTC)
STEP = timedelta(minutes=15)
B0 = datetime(2026, 8, 14, tzinfo=UTC)
CAD = J.DEFAULT_CADENCE_SECONDS
BB = int(B0.timestamp() // CAD)
TFS = list(STORAGE_TIMEFRAMES)
P = SYMBOL_ROTATION_PERIOD

# The sizes the review named, plus both ends of the allowed range. The ones that
# share a factor with 4 (56, 60, 64, ...) are the ones that used to fail.
SIZES = [4, 8, 12, 16, 20, 24, 55, 56, 57, 58, 59, 60, 61, 63, 64, 127, 128, 249, 250]
STRIDES = [1, 2, 3, 4, 5, 7, 8, 16]
REACHED = [1, 2, 3, 4, 8]


def offsets(n, stride, runs, base=BB):
    return [rotation_offset(n, now=B0 + timedelta(seconds=CAD * (j * stride)))
            for j in range(runs)]


def reached_symbols(n, k, stride, runs):
    """Which symbols get attempted when only `k` are reached per run.

    The run order is `selected[off:] + selected[:off]`, so the symbols reached
    are the k that follow `off` cyclically. This mirrors the committed traversal;
    `test_the_model_matches_the_committed_traversal` proves the mirror is exact.
    """
    seen = set()
    for j in range(runs):
        off = rotation_offset(n, now=B0 + timedelta(seconds=CAD * (j * stride)))
        seen |= {(off + i) % n for i in range(k)}
    return seen


# ══ THE CONSTANT ITSELF ════════════════════════════════════════════════════
def test_the_period_is_prime():
    assert P > 1 and all(P % d for d in range(2, int(P ** 0.5) + 1)), \
        f"{P} is not prime — gcd(stride, period) = 1 no longer holds for all strides"


def test_the_period_exceeds_the_universe_cap():
    """Without this, `x % count` over 0..period-1 is not onto 0..count-1."""
    assert P > UNIVERSE_CAP


def test_a_period_that_shares_a_factor_would_reintroduce_the_lock():
    """Falsification: the SAME code with a composite period starves again, so
    the guarantee is carried by the constant and not by the surrounding code."""
    n, stride, bad_period = 56, 4, 56
    seen = set()
    for j in range(P * 4):
        bucket = BB + j * stride
        seen.add((bucket % bad_period) % n)
    assert len(seen) < n, "the falsification case failed to falsify"
    good = {(BB + j * stride) % P % n for j in range(P * 4)}
    assert good == set(range(n)), "the real period failed to cover"


# ══ SYMBOL FAIRNESS UNDER EVERY STRIDE × SIZE × TRUNCATION ═════════════════
@pytest.mark.parametrize("n", SIZES)
@pytest.mark.parametrize("stride", STRIDES)
def test_every_start_position_occurs_within_one_period(n, stride):
    assert set(offsets(n, stride, P)) == set(range(n)), \
        f"n={n} stride={stride} never visited every start position in {P} runs"


@pytest.mark.parametrize("n", [4, 8, 16, 24, 56, 57, 58, 60, 64, 128, 249, 250])
@pytest.mark.parametrize("stride", STRIDES)
@pytest.mark.parametrize("k", REACHED)
def test_no_symbol_is_unreachable_under_budget_truncation(n, stride, k):
    """Blocker B, the exact shape that failed: gcd(stride, n) > 1 with k < 4."""
    seen = reached_symbols(n, k, stride, P)
    assert seen == set(range(n)), \
        f"n={n} stride={stride} k={k}: {n - len(seen)} symbols never reached"


def test_the_worst_gap_between_two_reaches_is_within_the_period():
    """The bound is not merely finite — it is the stated 251."""
    n, k, worst = 56, 1, 0
    for stride in STRIDES:
        last = {}
        for j in range(P * 3):
            off = rotation_offset(n, now=B0 + timedelta(seconds=CAD * (j * stride)))
            for s in {(off + i) % n for i in range(k)}:
                if s in last:
                    worst = max(worst, j - last[s])
                last[s] = j
    assert worst <= P, f"a symbol waited {worst} executed runs, above the bound {P}"


def test_the_excluded_case_is_a_stride_that_is_a_multiple_of_the_period():
    """Stated, not hidden: this is the one stride the scheme cannot defeat, and
    it means executing once per ~5.2 days forever. Asserting it keeps the
    documented limit honest — if a future change silently 'fixed' it, the
    docstring in `rotation_offset` would be wrong and this would say so."""
    seen = {rotation_offset(56, now=B0 + timedelta(seconds=CAD * (j * P)))
            for j in range(P)}
    assert len(seen) == 1, "the documented excluded case no longer behaves as documented"


# ══ RESTART / REDEPLOY / RELOAD ════════════════════════════════════════════
def test_rotation_is_restart_and_redeploy_independent():
    """Clock-derived, so there is no cursor a restart could lose."""
    import importlib
    ts = [B0 + timedelta(seconds=CAD * i) for i in (0, 1, 7, 250, 251, 252, 10 ** 5)]
    before = [rotation_offset(57, now=t) for t in ts]
    importlib.reload(J)
    after = [J.rotation_offset(57, now=t) for t in ts]
    assert before == after


def test_no_salted_hash_reaches_the_ordering():
    """Builtin hash() is salted per process; it would make fairness depend on
    which process happens to be running. AST, not substring: prose may mention
    it, a call may not."""
    import ast
    import inspect
    tree = ast.parse(inspect.getsource(J.rotation_offset).lstrip())
    calls = {getattr(nd.func, "id", None) for nd in ast.walk(tree)
             if isinstance(nd, ast.Call)}
    assert "hash" not in calls


def test_no_process_local_counter_backs_the_rotation():
    """A module-level cursor would reset on redeploy and silently re-favour the
    same symbols after every deploy."""
    import inspect
    src = inspect.getsource(J.rotation_offset)
    assert "global" not in src


# ══ UNIVERSE CHURN ═════════════════════════════════════════════════════════
@pytest.mark.parametrize("a,b", [(55, 56), (56, 57), (57, 56), (57, 58), (58, 59),
                                 (59, 60), (60, 61), (63, 64), (64, 63),
                                 (249, 250), (250, 249)])
def test_stable_symbols_regain_the_bound_after_churn_settles(a, b):
    """Fairness during unbounded adversarial churn is not claimed. What is
    claimed: once the universe stabilises, every symbol is reachable again
    within one period."""
    core = min(a, b)
    seen = set()
    for j in range(300 + P):
        n = ((a if j % 2 else b) if j < 300 else b)
        off = rotation_offset(n, now=B0 + timedelta(seconds=CAD * j))
        if j >= 300:
            seen.add(off % core)
    assert seen == set(range(core)), f"{a}->{b}: {core - len(seen)} symbols still unreached"


# ══ DEGENERATE INPUT ═══════════════════════════════════════════════════════
def test_degenerate_inputs():
    assert rotation_offset(0, now=B0) == 0
    assert rotation_offset(1, now=B0) == 0
    for n in (1, 2, 56, 57, 250):
        assert 0 <= rotation_offset(n, now=B0) < n
    with pytest.raises(ValueError, match="cadence_seconds"):
        rotation_offset(10, now=B0, cadence_seconds=0)
    with pytest.raises(ValueError, match="period"):
        rotation_offset(10, now=B0, period=0)


def test_rotation_is_not_a_candle_authority():
    """The clock buckets the ORDER; closure stays the exchange's job."""
    import inspect
    src = inspect.getsource(J.rotation_offset)
    assert "close" not in src and "watermark" not in src


# ══ THE MODEL USED ABOVE IS THE REAL TRAVERSAL ═════════════════════════════
@pytest.mark.asyncio
async def test_the_model_matches_the_committed_traversal():
    """`reached_symbols` assumes the run order is `selected[off:] + selected[:off]`
    and that every timeframe of a reached symbol is attempted. Both are checked
    here against the real `collect_once`, so the matrices above are not testing
    a convenient fiction."""
    class Sess:
        async def __aenter__(self): return self
        async def __aexit__(self, *e): return False
        def begin_nested(self):
            class _SP:
                async def __aenter__(s): return s
                async def __aexit__(s, *e): return False
            return _SP()
        async def execute(self, *a, **k):
            class _R:
                rowcount = 1
                def all(s): return []
                def scalars(s):
                    class _S:
                        def all(x): return []
                    return _S()
            return _R()
        async def commit(self): return None
        async def rollback(self): return None

    class Col:
        def __init__(self): self.att = []
        async def fetch_ohlcv(self, sym, tf, limit=500, end_time_ms=None):
            self.att.append((sym, tf))
            idx = pd.DatetimeIndex([T0 + i * STEP for i in range(6)], tz=UTC)
            d = pd.DataFrame({"open": np.full(6, 100.0), "high": np.full(6, 110.0),
                              "low": np.full(6, 90.0), "close": np.full(6, 100.0),
                              "volume": np.full(6, 10.0)}, index=idx)
            d["close_time"] = [t + STEP for t in idx]
            return d

    for n in (4, 5, 6, 7, 8):
        syms = [f"S{i:02d}U" for i in range(n)]
        for j in range(6):
            col = Col()
            await J.collect_once(lambda: Sess(), col, symbols=list(syms),
                                 timeframes=TFS, spacing=0, item_budget=0.05,
                                 now=B0 + timedelta(seconds=CAD * j),
                                 result=CollectionResult())
            off = rotation_offset(n, now=B0 + timedelta(seconds=CAD * j))
            expected = [(s, tf) for s in list(syms[off:]) + list(syms[:off])
                        for tf in TFS]
            assert col.att == expected, f"n={n} j={j} traversal diverged"
