-- 0012: OHLCV collection progression — a durable "a run started" counter.
--
-- WHY THIS EXISTS
-- ---------------
-- A3c's symbol rotation derived its phase from an ABSOLUTE CADENCE BUCKET
-- (floor(now/cadence)). Three independent reviews showed that family cannot carry
-- a fairness proof, because the ENVIRONMENT — not the collector — decides which
-- buckets are ever executed:
--
--   * `bucket % N` collapses to the coset generated by gcd(stride, N): at N=56
--     with an every-4th-cadence execution pattern, 42 of 56 symbols were measured
--     as never reached, forever.
--   * projecting through a prime (`(bucket % 251) % N`) removes THAT hole but
--     leaves one at stride 251, and moving the prime only moves the hole —
--     measured identical at 251, 257, 509 and 65537.
--
-- The defect is architectural: any function of wall-clock time can be phase-locked
-- by an execution pattern nobody enforces. Production has no persistent APScheduler
-- jobstore, no minimum-uptime invariant and no recovery guarantee, so no such
-- pattern is excluded.
--
-- The fix is to stop asking the clock. This counter advances once per EXECUTED
-- run, so the traversal offset becomes `run_seq % N` and every symbol is first at
-- least once within N executed runs — for ANY wall-clock execution pattern,
-- including total downtime, restarts and redeploys.
--
-- WHAT THE VALUE MEANS — EXACTLY
-- ------------------------------
-- "A collection run for this source HAS STARTED." Nothing else. It is deliberately
-- NOT a claim that the run succeeded, completed, attempted every symbol, attempted
-- every timeframe, persisted any bar, advanced coverage or advanced a watermark.
-- A run that increments this and then dies immediately still consumed a sequence
-- value, and that is the intended behaviour: it is what stops a repeatedly
-- crashing run from replaying the same prefix of the universe forever.
--
-- THIS IS NOT A COVERAGE CURSOR. It carries no information about which bars exist,
-- which are missing, or how far back history reaches. Historical completeness and
-- gap repair remain A4's, and reading this value can never answer an A4 question.
--
-- ADDITIVE ONLY. This migration does not touch `ohlcv_bars`, does not alter 0011,
-- and removes nothing. Rollback drops only the table created here; no OHLCV row is
-- ever at risk.
--
-- NOTE ON create_all: scripts/migrate.py runs Base.metadata.create_all BEFORE the
-- pending .sql files, so on a fresh database the MODEL creates this table and the
-- CREATE TABLE below is a no-op. Every constraint that carries correctness is
-- therefore declared in app/models/ohlcv_progress.py as well; the two are asserted
-- to agree in tests/test_ohlcv_progression.py.

CREATE TABLE IF NOT EXISTS ohlcv_collection_progress (
    -- Logical key. Matches the `source` used by the watermark read and the row
    -- write, so a second venue can never advance binance's fairness sequence.
    source      TEXT        NOT NULL,

    -- The progression itself. Monotonic, advanced by exactly one per executed run.
    run_seq     BIGINT      NOT NULL DEFAULT 0,

    -- NOT read by any correctness path. It exists because a shadow job's staleness
    -- is deliberately excluded from the global /health `degraded` aggregate, so a
    -- stalled cursor would otherwise be invisible: this is the only way an operator
    -- can distinguish "advancing" from "stuck since last week".
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- The primary key is deliberately UNNAMED. `create_all` runs first and emits
    -- PostgreSQL's default name, `ohlcv_collection_progress_pkey`; naming it here
    -- produced a table whose constraint names DIFFERED depending on which path
    -- built it — measured in an isolated PostgreSQL 17, and invisible to a static
    -- test that only checked the substring "primary key" was present in both.
    PRIMARY KEY (source),
    CONSTRAINT ck_ohlcv_collection_progress_seq CHECK (run_seq >= 0),
    CONSTRAINT ck_ohlcv_collection_progress_source CHECK (length(btrim(source)) > 0)
);

-- ROLLBACK (manual, additive-only reversal — never run against production without
-- an explicit checkpoint; it removes ONLY this table and touches no OHLCV data):
--
--   DROP TABLE IF EXISTS ohlcv_collection_progress;
--
-- Dormant A3c code tolerates the table being absent because nothing calls it; the
-- ACTIVATION checkpoint is what makes the table a hard requirement.
