// Legal content generator.
// Reads src/content/legal/<locale>/*.md, parses frontmatter, computes a SHA-256
// content hash, and writes typed, importable artifacts:
//   src/lib/legal/generated/meta.ts    (slug -> {title,version,effectiveDate,hash})
//   src/lib/legal/generated/bodies.ts  (slug -> markdown body)
// Everything is a bundled import (no runtime fs) so it works on Vercel/edge.
// Run: npm run legal:gen   (also wired as `prebuild`).

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LOCALE = 'tr';
const CONTENT_DIR = join(ROOT, 'src', 'content', 'legal', LOCALE);
const OUT_DIR = join(ROOT, 'src', 'lib', 'legal', 'generated');

// Display/footer order (legal docs are not alphabetical).
const PREFERRED_ORDER = [
  'kullanim-kosullari',
  'aydinlatma-metni',
  'acik-riza',
  'cerez-politikasi',
  'risk-bildirimi',
  'mesafeli-satis',
  'ticari-ileti',
];

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    data[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { data, body: m[2] };
}

const files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith('.md'));
const meta = {};
const bodies = {};
for (const f of files) {
  const raw = readFileSync(join(CONTENT_DIR, f), 'utf8');
  const { data, body } = parseFrontmatter(raw);
  const slug = data.slug || f.replace(/\.md$/, '');
  const normalized = body.replace(/\r\n/g, '\n').trim();
  const version = data.version || '0.0.0';
  const locale = data.locale || LOCALE;
  const hash = createHash('sha256')
    .update(`${locale}:${slug}:${version}:${normalized}`)
    .digest('hex');
  meta[slug] = { slug, title: data.title || slug, version, effectiveDate: data.effectiveDate || '', locale, hash };
  bodies[slug] = normalized;
}

const order = [
  ...PREFERRED_ORDER.filter((s) => meta[s]),
  ...Object.keys(meta).filter((s) => !PREFERRED_ORDER.includes(s)).sort(),
];

mkdirSync(OUT_DIR, { recursive: true });
const banner = '// AUTO-GENERATED by scripts/legal-gen.mjs — DO NOT EDIT. Run: npm run legal:gen\n';
writeFileSync(
  join(OUT_DIR, 'meta.ts'),
  banner +
    'export interface LegalDocMeta { slug: string; title: string; version: string; effectiveDate: string; locale: string; hash: string; }\n' +
    `export const LEGAL_ORDER: string[] = ${JSON.stringify(order, null, 2)};\n` +
    `export const LEGAL_META: Record<string, LegalDocMeta> = ${JSON.stringify(meta, null, 2)};\n`,
);
writeFileSync(
  join(OUT_DIR, 'bodies.ts'),
  banner + `export const LEGAL_BODIES: Record<string, string> = ${JSON.stringify(bodies, null, 2)};\n`,
);
console.log(`legal-gen: ${order.length} docs -> ${order.join(', ')}`);
