"""
Signal-related Pydantic schemas.

Covers signal listing, detail views, and performance tracking responses.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class _EmbeddedAsset(BaseModel):
    """Minimal asset info embedded in signal list items."""
    id: UUID
    symbol: str
    name: str
    asset_type: str
    market: Optional[str] = None

    model_config = {"from_attributes": True}


class SignalResponse(BaseModel):
    """Full signal for list views — includes all fields needed by the dashboard."""

    id: UUID
    asset_id: UUID
    asset: Optional[_EmbeddedAsset] = None
    signal_type: str
    confidence_score: float
    probability_score: Optional[float] = None
    risk_score: Optional[float] = None
    risk_level: str
    direction: str
    entry_zone_low: Optional[float] = None
    entry_zone_high: Optional[float] = None
    stop_loss: Optional[float] = None
    tp1: Optional[float] = None
    tp2: Optional[float] = None
    tp3: Optional[float] = None
    invalidation_conditions: Optional[str] = None
    explanation_tr: Optional[str] = None
    explanation_en: Optional[str] = None
    # engines_data may be a dict {engine_name: result} or a list [result, ...]
    # depending on how the AI orchestrator serialized it.
    engines_data: Optional[Any] = None
    timeframe: str
    is_active: bool
    generated_at: datetime
    expires_at: Optional[datetime] = None
    outcome: Optional[str] = None  # active / win / loss / breakeven / expired

    model_config = {"from_attributes": True}


class SignalDetailResponse(BaseModel):
    """Full signal detail response with all fields."""

    id: UUID
    asset_id: UUID
    signal_type: str
    confidence_score: float
    probability_score: Optional[float] = None
    risk_score: Optional[float] = None
    risk_level: str
    direction: str
    entry_zone_low: Optional[float] = None
    entry_zone_high: Optional[float] = None
    stop_loss: Optional[float] = None
    tp1: Optional[float] = None
    tp2: Optional[float] = None
    tp3: Optional[float] = None
    invalidation_conditions: Optional[str] = None
    engines_data: Optional[Any] = None
    explanation_tr: Optional[str] = None
    explanation_en: Optional[str] = None
    is_active: bool
    timeframe: str
    generated_at: datetime
    expires_at: Optional[datetime] = None
    performance: Optional["SignalPerformanceResponse"] = None

    model_config = {"from_attributes": True}


class SignalPerformanceResponse(BaseModel):
    """Signal performance tracking response."""

    id: UUID
    signal_id: UUID
    outcome: str
    actual_return: Optional[float] = None
    max_drawdown: Optional[float] = None
    hit_tp1: bool = False
    hit_tp2: bool = False
    hit_tp3: bool = False
    closed_at: Optional[datetime] = None
    is_expired: bool = False

    model_config = {"from_attributes": True}


class SignalListResponse(BaseModel):
    """Paginated list of signals."""

    items: List[SignalResponse] = Field(default_factory=list)
    total: int = 0
    page: int = 1
    page_size: int = 20
    total_pages: int = 0
    has_next: bool = False
    has_previous: bool = False


class SignalPerformanceSummary(BaseModel):
    """Aggregate performance statistics across signals."""

    total_signals: int = 0
    win_count: int = 0
    loss_count: int = 0
    breakeven_count: int = 0
    active_count: int = 0
    expired_count: int = 0
    win_rate: float = 0.0
    average_return: Optional[float] = None
    average_drawdown: Optional[float] = None
    tp1_hit_rate: float = 0.0
    tp2_hit_rate: float = 0.0
    tp3_hit_rate: float = 0.0
    
    # Enhanced metrics for dashboard additions
    win_rate_by_direction: Dict[str, float] = Field(default_factory=dict)
    win_rate_by_asset: Dict[str, float] = Field(default_factory=dict)
    performance_by_signal_type: Dict[str, Dict[str, Any]] = Field(default_factory=dict)
    historical_equity_curve: List[Dict[str, Any]] = Field(default_factory=list)
    drawdown_analysis: Dict[str, Any] = Field(default_factory=dict)


class BacktestRequest(BaseModel):
    """Configuration options for triggering a walk-forward backtest."""
    symbol: str
    timeframe: str = "1h"
    initial_capital: float = 10000.0
    risk_pct: float = 2.0
    max_age: int = 48
    execution_model: str = "conservative"


class BacktestResponse(BaseModel):
    """Report generated by a historical backtest run."""
    total_trades: int
    wins: int
    losses: int
    breakevens: int
    expired: int
    win_rate: float
    loss_rate: float
    profit_factor: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown_pct: float
    average_return_pct: float
    average_rr: float
    expectancy_pct: float
    max_consecutive_wins: int
    max_consecutive_losses: int
    equity_curve: List[Dict[str, Any]]
    trades_log: List[Dict[str, Any]]


# Resolve forward reference
SignalDetailResponse.model_rebuild()
